Repository woowacourse-teams/2025-bom-bom, pull requests merged in 2025-09, with the labels that each got.

#279 hotfix: 오늘 도착한 아티클의 경우만 펫 점수 올라가는 테스트 작성 및 수정
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/event/MarkAsReadListenerTest.java
Labels: hotfix, BE

#253 [BE][BOM-337] chore: 운영 서버 롤백 워크플로우 구축
  .github/workflows/server-prod-rollback.yml
Labels: chore, BE

#280 [FE][BOM-379] 최대 레벨 펫의 경험치 UI 수정
  frontend/src/components/PetCard/PetCard.constants.ts
  frontend/src/components/PetCard/PetCard.tsx
Labels: refactor, FE

#274 [BE][BOM-363] feat: 1시간마다 월별 순위 갱신, 나의 순위 조회 API 추가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/controller/ReadingController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/controller/ReadingControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/domain/LowestRankWithDifference.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/domain/MonthlyReading.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/MemberMonthlyReadingRankResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/scheduler/ReadingScheduler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
  backend/bom-bom-server/src/main/resources/db/migration/V1.1__monthly_reading_add_column.sql
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/service/ReadingServiceTest.java
Labels: feat, BE

#282 [FE][BOM-388] 애플 로그인 UI 구현
  frontend/public/assets/apple.svg
  frontend/src/pages/login/components/LoginCard.tsx
Labels: feat, FE

#285 [BE][BOM-389] fix: MonthlyReading의 rank 컬럼명 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/domain/MonthlyReading.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
  backend/bom-bom-server/src/main/resources/db/migration/V1.21__monthly_reading_change_column_name.sql
Labels: fix, BE

#286 [BE][BOM-390] fix: 회원가입 시 birthDate 필드 추가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
Labels: hotfix, BE

#297 [BE][BOM-395] fix: 애플 회원가입/로그인 시 리프레시 토큰 발급 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/client/AppleRevokeClient.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/PendingOAuth2Member.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/provider/impl/AppleOAuth2Provider.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/CustomOAuth2UserService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
Labels: fix, BE

#298 [FE][BOM-401] 앱 로고 변경
  app/android/app/src/main/res/drawable-hdpi/splashscreen_logo.png
  app/android/app/src/main/res/drawable-mdpi/splashscreen_logo.png
  app/android/app/src/main/res/drawable-xhdpi/splashscreen_logo.png
  app/android/app/src/main/res/drawable-xxhdpi/splashscreen_logo.png
  app/android/app/src/main/res/drawable-xxxhdpi/splashscreen_logo.png
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/android/app/src/main/res/values/colors.xml
  app/android/app/src/main/res/values/styles.xml
  app/app.json
  app/app/_layout.tsx
  app/app/assets/images/logo.png
  app/ios/app.xcodeproj/project.pbxproj
  app/ios/app/Images.xcassets/AppIcon.appiconset/App-Icon-1024x1024@1x.png
  app/ios/app/Images.xcassets/SplashScreenBackground.colorset/Contents.json
  app/ios/app/Images.xcassets/SplashScreenLogo.imageset/image.png
  app/ios/app/Images.xcassets/SplashScreenLogo.imageset/image@2x.png
  app/ios/app/Images.xcassets/SplashScreenLogo.imageset/image@3x.png
  app/ios/app/SplashScreen.storyboard
  frontend/public/assets/logo.png
Labels: refactor, FE

#314 [FE][BOM-412] GA 코드 적용
  frontend/src/components/Header/HeaderNavButtons.tsx
  frontend/src/components/Header/LoginButton.tsx
  frontend/src/components/PageTitle/PageTitle.ts
  frontend/src/libs/googleAnalytics/GAInitializer.tsx
  frontend/src/libs/googleAnalytics/constants.ts
  frontend/src/libs/googleAnalytics/initGA.ts
  frontend/src/libs/googleAnalytics/usePageTracking.ts
  frontend/src/pages/detail/components/ArticleBody/ArticleBody.tsx
  frontend/src/pages/detail/components/FloatingToolbar/useFloatingToolbarSelection.ts
  frontend/src/pages/detail/components/MemoCard/EditableMemoCard.tsx
  frontend/src/pages/detail/components/MemoPanel/MemoPanel.tsx
  frontend/src/pages/recommend/components/NewsletterDetail/NewsletterDetail.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/NewsletterHero/NewsletterHero.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/signup/components/SignupCard.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/routes/__root.tsx
  frontend/src/routes/_bombom.tsx
Labels: chore, FE

#312 [FE][BOM-392] SEO 관련 세팅
  frontend/index.html
  frontend/robots.txt
  frontend/sitemap.xml
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/articles.guide.$guideId.tsx
  frontend/src/routes/_bombom/bookmark.tsx
  frontend/src/routes/_bombom/guide.tsx
  frontend/src/routes/_bombom/index.tsx
  frontend/src/routes/_bombom/memo.tsx
  frontend/src/routes/_bombom/storage.tsx
  frontend/src/routes/signup.tsx
Labels: chore, FE

#316 chore: 배포 환경에 따라 robots.txt의 내용을 다르게 설정하도록 파일 분리
  .github/workflows/frontend-ci-cd.yml
  frontend/public/robots.dev.txt
  frontend/public/robots.prod.txt
  frontend/public/sitemap.xml
Labels: chore, FE

#321 [BE][BOM-423] feat: 모바일 앱에서 애플 원탭 로그인 API 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/AppleClientSecretSupplier.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/request/NativeLoginRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/AppleOAuth2Service.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/CustomOAuth2UserService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/GoogleOAuth2LoginService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/IdTokenValidator.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/OAuth2LoginService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SecurityConfig.java
Labels: feat, BE

#322 [FE][BOM-410] expo 앱 이름 변경
  app/.prettierrc
  app/app.json
  app/ios/Podfile.properties.json
  app/ios/app.xcodeproj/project.pbxproj
  app/ios/app/Info.plist
  app/package-lock.json
  app/package.json
Labels: fix, FE

#315 [FE][BOM-403] 이달의 독서왕 나의 순위 추가
  frontend/src/apis/members.ts
  frontend/src/apis/queries.ts
  frontend/src/pages/recommend/components/NewsletterHero/NewsletterHero.stories.tsx
  frontend/src/pages/recommend/components/NewsletterHero/NewsletterHero.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboardItem.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingMyRank.tsx
  frontend/src/pages/recommend/components/TrendySection/TrendySection.tsx
  frontend/src/routes/_bombom/recommend.tsx
  frontend/src/types/openapi.d.ts
Labels: feat, FE

#303 [FE][BOM-382] 뉴스레터 읽기 페이지 및 바로가기 메뉴 페이지 ux 개선
  frontend/public/assets/chevron-down.svg
  frontend/public/assets/chevron-left.svg
  frontend/public/assets/help.svg
  frontend/public/assets/memo.svg
  frontend/src/components/Header/DetailPageHeader.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/MobileHeader.tsx
  frontend/src/components/Header/PCHeader.tsx
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/hooks/useActiveNav.ts
  frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx
  frontend/src/pages/detail/components/FloatingActionButtons/FloatingActionButtons.tsx
  frontend/src/pages/detail/components/MemoPanel/MemoPanel.tsx
  frontend/src/pages/storage/components/QuickMenu/QuickMenu.constants.ts
  frontend/src/pages/storage/components/QuickMenu/QuickMenu.tsx
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/bookmark.tsx
  frontend/src/routes/_bombom/guide.tsx
  frontend/src/routes/_bombom/memo.tsx
  frontend/src/routes/_bombom/storage.tsx
Labels: refactor, FE

#325 [BE][BOM-425] fix: 회원가입 시 성별 Optional 적용
  backend/bom-bom-server/docker-compose-dev.yml
  backend/bom-bom-server/docker-compose-prod-sub.yml
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/request/MemberSignupRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/enums/Gender.java
  backend/bom-bom-server/src/main/resources/db/migration/V2.40__add_gender_none.sql
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/auth/controller/AuthControllerTest.java
Labels: fix, BE

#326 [FE][BOM-426] 회원 가입 정보를 옵셔널로 변경
  frontend/src/pages/signup/components/SignupCard.tsx
  frontend/src/pages/signup/components/SignupCard.types.ts
  frontend/src/pages/signup/components/SignupCard.utils.ts
  frontend/src/styles/theme.ts
  frontend/src/types/openapi.d.ts
Labels: refactor, FE

#332 [BE][BOM-433] fix: 두개의 인스턴스에서 스케줄러가 모두 실행되는 문제 해결
  backend/bom-bom-server/build.gradle.kts
  backend/bom-bom-server/src/main/java/me/bombom/BomBomServerApplication.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/ShedLockConfig.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/scheduler/ReadingScheduler.java
  backend/bom-bom-server/src/main/resources/db/migration/V3.00__create_shedlock_table.sql
Labels: fix, BE

#337 [BE][BOM-440] fix: 회원가입시 받는 nickname, email 정규식 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/request/MemberSignupRequest.java
Labels: fix, BE

#342 [FE][BOM-445] GA user id 세팅 오류 해결
  frontend/src/routes/_bombom.tsx
Labels: fix, FE

#362 [BE][BOM-447] 뉴스레터 인증 메일 테이블 추가
  backend/bom-bom-server/src/main/resources/db/migration/V4.0.0_create_newsletter_verification.sql
Labels: feat

#349 [BE][BOM-355] 인증 메일을 보낼 때 기존 뉴스레터 이메일과 다를 때도 처리할 수 있는 로직 추가
  backend/mail-server/src/main/java/news/bombomemail/article/service/ArticleService.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/AlternativeMultipartExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/ContentExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/EmailContentExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/HtmlTextExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/MultipartExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/PlainTextExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/Rfc822Extractor.java
  backend/mail-server/src/main/java/news/bombomemail/email/service/EmailService.java
  backend/mail-server/src/main/java/news/bombomemail/email/util/EmailContentExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/newsletter/domain/NewsletterVerification.java
  backend/mail-server/src/main/java/news/bombomemail/newsletter/repository/NewsletterVerificationRepository.java
  backend/mail-server/src/test/java/news/bombomemail/article/ArticleServiceTest.java
Labels: feat, BE

#367 [BE][BOM-482] fix: html 파싱 오류 해결
  backend/mail-server/src/main/java/news/bombomemail/email/extractor/HtmlTextExtractor.java
Labels: feat, BE

#370 [FE][BOM-481] 매일메일 긱뉴스 깨지는거 확인
  frontend/src/pages/detail/components/ArticleBody/ArticleBody.tsx
  frontend/src/pages/detail/components/ArticleContent/ArticleContent.tsx
  frontend/src/pages/detail/components/ArticleContent/ArticleContent.utils.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/articles.guide.$guideId.tsx
  frontend/src/styles/reset.ts
Labels: fix, FE

#384 [FE][BOM-497] 웹에서 애플 로그인 버튼이 사라진 문제 수정
  frontend/src/libs/webview/webview.utils.ts
  frontend/src/pages/login/components/LoginCard.tsx
Labels: refactor, FE

#360 [BE][BOM-430] feat: 탈퇴 회원 정보 분리 및 90일 유지 후 삭제 추가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/repository/BookmarkRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/service/BookmarkService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/repository/HighlightRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/service/HighlightService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/PetRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/ContinueReadingRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingRealtimeRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingSnapshotRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/TodayReadingRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/WeeklyReadingRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/YearlyReadingRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/subscribe/repository/SubscribeRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/subscribe/service/SubscribeService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/domain/WithdrawnMember.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/DeleteArticlesByWithdrawListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/DeleteBookmarksByWithdrawListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/DeleteHighlightsByWithdrawListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/DeletePetByWithdrawListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/DeleteReadingsByWithdrawListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/DeleteSubscribeByWithdrawListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/event/WithdrawEvent.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/repository/WithdrawnMemberRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/scheduler/WithdrawScheduler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/withdraw/service/WithdrawService.java
  backend/bom-bom-server/src/main/resources/db/migration/V5.0.0__create_withdrawn_member_table.sql
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberWithdrawIntegrationTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/service/MemberServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/withdraw/service/WithdrawServiceTest.java
Labels: feat, BE

#393 [BE][BOM-506] feat: 회원가입 필드 검증 api에 형식 검증 추가, 중복 시 랜덤값 생성
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/AppleAuthRequestEntityConverter.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AppleCallbackController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/request/SignupValidateRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/enums/DuplicateFieldConverter.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/enums/SignupValidateField.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/enums/SignupValidateStatus.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/extractor/AppleUserInfoExtractor.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/handler/OAuth2LoginSuccessHandler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/AppleOAuth2Service.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/util/UniqueUserInfoGenerator.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/util/UserInfoValidator.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/ErrorDetail.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/request/MemberSignupRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
  backend/bom-bom-server/src/main/resources/db/migration/V6.3.0__increase_member_nickname_length_to_50.sql
Labels: feat, BE

#394 [BE][BOM-493] test: 테스트 DB MySQL 적용
  .github/workflows/dev-pull-request.yml
  backend/bom-bom-server/build.gradle.kts
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/controller/ArticleControllerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/service/ArticleServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/auth/controller/AuthControllerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/bookmark/controller/BookmarkControllerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/bookmark/service/BookmarkServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/guidemail/service/GuideMailServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/highlight/controller/HighlightControllerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/highlight/service/HighlightServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberSignupListenerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberWithdrawIntegrationTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/service/MemberServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/newsletter/service/NewsletterServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/service/PetServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/service/ReadingServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/withdraw/service/WithdrawServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/support/IntegrationTest.java
  backend/bom-bom-server/src/test/java/me/bombom/support/TestcontainerConfig.java
Labels: test, BE

#416 [BE][BOM-525] feat: 앱 로그인 시 유니크한 닉네임, 이메일을 클라이언트에게 넘겨주도록 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/NativeLoginResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/dto/request/NativeLoginRequest.java
Labels: feat, BE
