Repository woowacourse-teams/2025-bom-bom, pull requests merged in 2025-08, with the labels that each got.

#126 [BE][BOM-208] feat: NewsletterDetail에 발신자 필드 추가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/NewsletterDetail.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
Labels: feat, BE

#132 [FE][BOM-203] feat: 펫키우기 퍼블리싱
  frontend/public/assets/pet-example.png
  frontend/public/assets/pet.svg
  frontend/src/components/PetCard/PetCard.tsx
  frontend/src/components/ProgressBar/ProgressBar.stories.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/pages/today/components/EmptyLetterCard/EmptyLetterCard.tsx
  frontend/src/routes/_bombom/index.tsx
Labels: feat, FE

#136 [FE][BOM-199] feat: 로그인한 사용자의 추천페이지 배너 구현
  frontend/public/assets/carousel-arrow-next.png
  frontend/public/assets/carousel-arrow-prev.png
  frontend/src/components/Carousel/Carousel.stories.tsx
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/components/Carousel/useCarousel.ts
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/NewsletterHero/NewsletterHero.tsx
  frontend/src/pages/recommend/components/SlideCardList/SlideCardList.tsx
Labels: feat, FE

#98 [FE][BOM-165] feat: openapi-typescript 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/articles.ts
  frontend/src/apis/auth.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/members.ts
  frontend/src/apis/newsLetters.ts
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/mocks/datas/articles.ts
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.stories.tsx
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/signup/components/SignupCard.tsx
  frontend/src/pages/storage/utils/getArticleReadStats.ts
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCard.tsx
  frontend/src/pages/today/types/article.ts
  frontend/src/pages/today/types/category.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/index.tsx
  frontend/src/routes/_bombom/storage.tsx
  frontend/src/types/articles.ts
  frontend/src/types/openapi.d.ts
  frontend/tsconfig.json
Labels: feat, FE

#134 [FE][BOM-216] feat: 로컬에서 로그인 시, 로컬로 redirect되게 수정
  frontend/src/apis/env.ts
  frontend/src/pages/login/components/LoginCard.tsx
Labels: feat, FE

#140 [BE][BOM-200] feat: 메모 기능 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/controller/HighlightController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/domain/Highlight.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/request/ChangeHighlightColorRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/request/HighlightCreateRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/request/HighlightLocationRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/request/UpdateHighlightRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/response/HighlightResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/service/HighlightService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/highlight/service/HighlightServiceTest.java
Labels: feat, BE

#128 [FE][BOM-178] feat: 스크롤 위치 저장 기능 구현
  frontend/src/constants/article.ts
  frontend/src/hooks/useScrollRestoration.ts
  frontend/src/hooks/useScrollThreshold.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/utils/localStorage.test.ts
  frontend/src/utils/localStorage.ts
Labels: feat, FE

#147 [FE][BOM-218] feat: 오늘 안읽은 뉴스레터 클릭 기능 추가
  frontend/src/apis/articles.ts
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/index.tsx
Labels: feat, FE

#143 [BE][BOM-202] feat: 키우기 관련 기능 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/CustomArticleRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/CServerErrorException.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/GlobalExceptionHandler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/ScorePolicyConstants.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/controller/PetController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Pet.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Stage.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/dto/PetResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/event/AddArticleScoreEvent.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/event/AddArticleScoreListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/PetRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/StageRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberSignupListenerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/event/AddArticleScoreListenerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/service/PetServiceTest.java
Labels: feat, BE

#146 [FE][BOM-217] feat: highlight 메모 기능 추가
  frontend/src/apis/fetcher.ts
  frontend/src/apis/highlight.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/detail/components/FloatingToolbar/FloatingToolbar.tsx
  frontend/src/pages/detail/components/MemoCard/MemoCard.tsx
  frontend/src/pages/detail/components/MemoPanel/MemoPanel.tsx
  frontend/src/pages/detail/hooks/useHighlightData.ts
  frontend/src/pages/detail/hooks/useHighlightHoverEffect.ts
  frontend/src/pages/detail/types/highlight.ts
  frontend/src/pages/detail/utils/highlight.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
Labels: feat, FE

#145 [BE][BOM-222] feat: 북마크 기능 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/domain/Article.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/CustomArticleRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/controller/BookmarkController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/domain/Bookmark.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/dto/response/BookmarkResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/dto/response/BookmarkStatusResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/repository/BookmarkRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/repository/BookmarkRepositoryImpl.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/repository/CustomBookmarkRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/service/BookmarkService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/ErrorDetail.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/service/HighlightService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestJpaAuditingConfig.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/bookmark/service/BookmarkServiceTest.java
Labels: feat, BE

#149 [FE][BOM-223] feat: 펫 추가 및 애니메이션
  frontend/public/assets/pet-1-lv1.png
  frontend/public/assets/pet-1-lv2.png
  frontend/public/assets/pet-1-lv3.png
  frontend/public/assets/pet-1-lv4.png
  frontend/public/assets/pet-1-lv5.png
  frontend/public/assets/pet-example.png
  frontend/src/apis/pet.ts
  frontend/src/components/PetCard/PetCard.constants.ts
  frontend/src/components/PetCard/PetCard.keyframes.ts
  frontend/src/components/PetCard/PetCard.tsx
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/types/openapi.d.ts
Labels: feat, FE

#164 [BE][BOM-244] refactor: 북마크 dto 평탄화
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/dto/response/BookmarkResponse.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/bookmark/service/BookmarkServiceTest.java
Labels: refactor, BE

#163 [FE][BOM-227] feat: 하이라이트 클릭 시, 하이라이트 삭제 및 메모 기능 추가
  frontend/public/assets/edit-off.svg
  frontend/public/assets/edit.svg
  frontend/public/assets/pen.svg
  frontend/src/pages/detail/components/ArticleContent/ArticleContent.tsx
  frontend/src/pages/detail/components/FloatingToolbar/FloatingToolbar.tsx
  frontend/src/pages/detail/components/FloatingToolbar/FloatingToolbar.types.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
Labels: feat, FE

#169 [FE][BOM-249] chore: 페이지네이션 size page 수정
  frontend/src/routes/_bombom/storage.tsx
Labels: chore, FE

#157 [BE][BOM-173] feat: 환경 별 Swagger 분리 및 API 설정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SecurityConfig.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SwaggerConfig.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/resolver/LoginMember.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/controller/HighlightController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/controller/HighlightControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/controller/MemberController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/controller/MemberControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/controller/NewsletterController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/controller/NewsletterControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/controller/PetController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/controller/PetControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/PetRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/controller/ReadingController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/controller/ReadingControllerApi.java
Labels: feat, BE

#174 [BE][BOM-237] feat: 멤버별 하이라이트 조회 API 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/controller/HighlightController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/controller/HighlightControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/response/HighlightLocationResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/response/HighlightResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/repository/CustomHighlightRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/repository/HighlightRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/repository/HighlightRepositoryImpl.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/service/HighlightService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/NewsletterRepository.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/highlight/service/HighlightServiceTest.java
Labels: feat, BE

#178 [BE][BOM-253] feat: 레벨업(score 갱신 시 stage 함께 갱신)
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Pet.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Stage.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/StageRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/event/AddArticleScoreListenerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/pet/service/PetServiceTest.java
Labels: feat, BE

#179 [FE][BOM-255]: feat: react ga4 적용
  frontend/src/components/Header/Header.tsx
  frontend/src/libs/googleAnalytics/GAInitializer.tsx
  frontend/src/libs/googleAnalytics/gaEvents.ts
  frontend/src/libs/googleAnalytics/initGA.ts
  frontend/src/libs/googleAnalytics/usePageTracking.ts
  frontend/src/main.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/routes/__root.tsx
Labels: feat, FE

#188 [BE][BOM-262] 잘못 전달하는 ID 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Pet.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/domain/Stage.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/repository/PetRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/event/UpdateReadingCountEvent.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/event/UpdateReadingCountListener.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/event/UpdateReadingCountListenerTest.java
Labels: fix, BE

#185 [BE][BOM-259] fix: 아티클 조회 페이지네이션 getTotal 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
Labels: fix, BE

#189 [FE][Bom-263] fix: 키우기 이미지 안나오는 오류
  frontend/src/components/PetCard/PetCard.tsx
Labels: fix, FE

#192 [FE][BOM-267] fix: GA 오류 수정
  frontend/src/libs/googleAnalytics/GAInitializer.tsx
  frontend/src/libs/googleAnalytics/initGA.ts
Labels: fix, FE

#184 [FE][BOM-233] refactor: 북마크 api 연결 및 토스트 추가
  frontend/src/apis/bookmark.ts
  frontend/src/apis/queries.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Toast/Toast.tsx
  frontend/src/components/Toast/useToast.ts
  frontend/src/libs/googleAnalytics/GAInitializer.tsx
  frontend/src/libs/googleAnalytics/gaEvents.ts
  frontend/src/libs/googleAnalytics/initGA.ts
  frontend/src/libs/googleAnalytics/usePageTracking.ts
  frontend/src/main.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/handlers/bookmark.ts
  frontend/src/pages/detail/components/FloatingActionButtons/FloatingActionButtons.tsx
  frontend/src/pages/detail/hooks/useBookmarkMutation.ts
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/routes/__root.tsx
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/bookmark.tsx
Labels: feat, FE

#183 [FE][BOM-258] fix: 헤더 info 레이아웃 시프트 방지
  frontend/src/components/Header/Header.tsx
Labels: fix, FE

#193 [FE][BOM-268] fix: 총 개수 수정
  frontend/src/routes/_bombom/storage.tsx
Labels: fix, FE

#202 [FE][BOM-284] feat: useMediaQuery 훅
  frontend/src/constants/device.ts
  frontend/src/hooks/useDeviceType.ts
  frontend/src/hooks/useMediaQuery.ts
Labels: feat, FE

#201 [FE][BOM-194] refactor: article read page 리팩토링
  frontend/src/apis/bookmark.ts
  frontend/src/apis/queries.ts
  frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx
  frontend/src/pages/detail/components/TodayUnreadArticlesSection/TodayUnreadArticlesSection.tsx
  frontend/src/pages/detail/hooks/useAddBookmarkMutation.ts
  frontend/src/pages/detail/hooks/useArticleBookmark.ts
  frontend/src/pages/detail/hooks/useBookmarkMutation.ts
  frontend/src/pages/detail/hooks/useMarkArticleAsReadMutation.ts
  frontend/src/pages/detail/hooks/useRemoveBookmarkMutation.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
Labels: refactor, FE

#210 [BE][BOM-294] feat: 뉴스레터별 아티클 조회
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCategoryStatisticsResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCountPerCategoryResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCountPerNewsletterResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleNewsletterStatisticsResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticlesOptions.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/CustomArticleRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/NewsletterRepository.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/controller/ArticleControllerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/service/ArticleServiceTest.java
Labels: feat, BE

#211 [BE][BOM-289] fix: swagger에서 필수값으로 나타나도록 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/ArticleDetailResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/ArticleResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCountPerNewsletterResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleNewsletterStatisticsResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/dto/response/BookmarkResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/dto/response/BookmarkStatusResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/response/HighlightLocationResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/dto/response/HighlightResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/response/MemberProfileResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterBasicResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterSummaryResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/dto/PetResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/ReadingInformationResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/TodayReadingResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/WeeklyCurrentCountResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/WeeklyGoalCountResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/WeeklyReadingResponse.java
Labels: fix, BE

#205 [FE][BOM-277] refactor: 헤더 반응형 적용
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/HeaderLogo.tsx
  frontend/src/components/Header/HeaderNavButtons.tsx
  frontend/src/components/Header/HeaderProfile.tsx
  frontend/src/styles/theme.ts
Labels: refactor, FE

#206 [FE][BOM-290] feat: 플로팅 버튼
  frontend/public/assets/link.svg
  frontend/src/components/FloatingActionButton/FloatingActionButton.stories.tsx
  frontend/src/components/FloatingActionButton/FloatingActionButton.tsx
  frontend/src/pages/storage/components/QuickMenu/QuickMenu.tsx
Labels: feat, FE

#212 [FE][BOM-277] refactor: 키우기, 읽기 현황 컴포넌트 반응형 구현
  frontend/src/components/PetCard/PetCard.tsx
  frontend/src/components/ProgressWithLabel/ProgressWithLabel.tsx
  frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCard.tsx
  frontend/src/pages/today/components/StreakCounter/StreakCounter.tsx
  frontend/src/routes/_bombom/index.tsx
  frontend/src/types/openapi.d.ts
Labels: refactor, FE

#214 [BE][BOM-286] feat: 로깅 시스템 구축
  backend/bom-bom-server/build.gradle.kts
  backend/bom-bom-server/src/main/java/me/bombom/api/log/MDCLoggingFilter.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/enums/OAuth2Provider.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/bookmark/service/BookmarkService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/WebConfig.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/CIllegalArgumentException.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/CServerErrorException.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/ErrorContextKeys.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/GlobalExceptionHandler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/UnauthorizedException.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/highlight/service/HighlightService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/logging/LoggingInterceptor.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/controller/NewsletterControllerApi.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/pet/service/PetService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/event/UpdateReadingCountListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
  backend/bom-bom-server/src/main/resources/logback-common.xml
  backend/bom-bom-server/src/main/resources/logback-dev.xml
  backend/bom-bom-server/src/main/resources/logback-prod.xml
  backend/bom-bom-server/src/main/resources/logback-spring.xml
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/event/UpdateReadingCountListenerTest.java
Labels: feat, BE

#218 [FE][BOM-295] feat: 북마크 모아보기
  frontend/public/assets/news.svg
  frontend/src/apis/articles.ts
  frontend/src/apis/bookmark.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/queries.ts
  frontend/src/components/Tab/Tab.tsx
  frontend/src/mocks/handlers.ts
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.stories.tsx
  frontend/src/pages/storage/components/CategoryFilter/CategoryFilter.stories.tsx
  frontend/src/pages/storage/components/NewsletterFilter/NewsletterFilter.stories.tsx
  frontend/src/pages/storage/components/NewsletterFilter/NewsletterFilter.tsx
  frontend/src/pages/storage/components/PCStorageContent/PCStorageContent.tsx
  frontend/src/pages/storage/hooks/useStorageFilters.ts
  frontend/src/routes/_bombom/bookmark.tsx
  frontend/src/routes/_bombom/storage.tsx
  frontend/src/types/articles.ts
Labels: feat, FE

#233 [BE][BOM-334] feat: 아티클 하이라이트 목록 조회 swagger 추가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleControllerApi.java
Labels: feat, BE

#232 [FE][BOM-297] 뉴스레터 상세 모달
  frontend/public/assets/article-history.svg
  frontend/public/assets/home.svg
  frontend/src/apis/newsLetters.ts
  frontend/src/apis/queries.ts
  frontend/src/components/FloatingActionButton/FloatingActionButton.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/HeaderProfile.tsx
  frontend/src/components/Modal/Modal.tsx
  frontend/src/components/Modal/useModal.ts
  frontend/src/components/Select/Select.tsx
  frontend/src/components/Toast/Toast.tsx
  frontend/src/hooks/useKeydownEscape.ts
  frontend/src/mocks/datas/newsletterDetail.ts
  frontend/src/mocks/datas/trendyNewsLetter.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/handlers/newsletterDetail.ts
  frontend/src/pages/detail/components/FloatingToolbar/FloatingToolbar.tsx
  frontend/src/pages/detail/components/MemoPanel/MemoPanel.tsx
  frontend/src/pages/recommend/components/NewsletterDetail/NewsletterDetail.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/NewsletterHero/NewsletterHero.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/signup/components/SignupCard.tsx
  frontend/src/pages/today/components/StreakCounter/StreakCounter.tsx
  frontend/src/styles/theme.ts
  frontend/src/types/newsletter.ts
  frontend/src/types/openapi.d.ts
  frontend/src/utils/externalLink.ts
Labels: feat, FE

#234 [FE][BOM-296] 가이드 메일
  frontend/src/apis/guide.ts
  frontend/src/apis/highlight.ts
  frontend/src/hooks/useLocalStorageState.ts
  frontend/src/hooks/useScrollThreshold.ts
  frontend/src/mocks/datas/guideMail.ts
  frontend/src/mocks/handlers.ts
  frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx
  frontend/src/pages/detail/components/GuideArticleBody.tsx
  frontend/src/pages/detail/hooks/useArticleAsReadMutation.ts
  frontend/src/pages/detail/hooks/useGuideAsReadMutation.ts
  frontend/src/pages/detail/hooks/useHighlightData.ts
  frontend/src/pages/detail/hooks/useLocalHighlightData.ts
  frontend/src/pages/detail/types/highlight.ts
  frontend/src/pages/detail/utils/highlight.ts
  frontend/src/pages/signup/components/SignupCard.tsx
  frontend/src/pages/storage/components/QuickMenu/QuickMenu.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/articles.guide.$guideId.tsx
  frontend/src/routes/_bombom/guide.tsx
  frontend/src/routes/_bombom/index.tsx
  frontend/src/types/guide.ts
  frontend/src/utils/date.ts
  frontend/src/utils/localStorage.ts
Labels: feat, FE

#243 [FE][BOM-323] 아티클 카드 크기 줄이기
  frontend/src/pages/storage/components/ArticleList/ArticleList.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/routes/_bombom/index.tsx
Labels: refactor, FE

#247 [FE][BOM-346] 모달 홈페이지 링크 위치 변경
  frontend/src/components/Badge/Badge.tsx
  frontend/src/pages/recommend/components/NewsletterDetail/NewsletterDetail.tsx
Labels: refactor, FE

#246 [FE][BOM-351] 뉴스레터 상세 페이지 반응형
  frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx
  frontend/src/pages/detail/components/TodayUnreadArticlesSection/TodayUnreadArticlesSection.tsx
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/recommend.tsx
Labels: feat, FE

#251 [FE][BOM-354] 뉴스레터 보관함 반응형 디자인 수정
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/routes/_bombom/index.tsx
  frontend/src/routes/_bombom/recommend.tsx
  frontend/src/routes/_bombom/storage.tsx
  frontend/src/styles/theme.ts
Labels: refactor, FE

#252 [BE][BOM-358] fix: 이달의 독서왕 쿼리 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/dto/response/MonthlyReadingRankResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/repository/MonthlyReadingRepository.java
Labels: fix, BE

#245 [BE][BOM-343] feat: 회원 탈퇴 및 soft delete 기능 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/service/CustomOAuth2UserService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/exception/ErrorDetail.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/resolver/LoginMemberArgumentResolver.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/repository/MemberRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/scheduler/MemberCleanupScheduler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/service/MemberServiceTest.java
Labels: feat, BE

#248 [FE][BOM-330] 연령별 인기 뉴스레터 API 연결
  frontend/src/apis/members.ts
  frontend/src/apis/queries.ts
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
Labels: feat, FE

#258 [FE][BOM-356] 읽기 페이지 스크롤 진행도
  frontend/src/components/ProgressBar/ProgressBar.stories.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/hooks/useScrollProgress.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/styles/theme.ts
Labels: feat, FE

#261 [FE][BOM-366] 펫 카드 레이아웃 조정
  frontend/src/components/PetCard/PetCard.tsx
Labels: refactor, FE

#264 [FE][BOM-368] 페이지네이션에서 마지막 페이지가 추가되는 이슈
  frontend/src/components/Pagination/Pagination.utils.ts
Labels: fix, FE

#259 [FE][BOM-364] 로그인 요청 카드의 반응형 디자인 추가
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/components/RequireLoginCard/RequireLoginCard.tsx
Labels: feat, FE

#270 [FE][BOM-331] 새로고침 스크롤 미복원 이슈 해결
  frontend/src/hooks/useScrollRestoration.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
Labels: fix, FE

#265 [FE][BOM-367] 모바일 환경 가이드의 북마크 제거
  frontend/src/pages/detail/components/ArticleHeader/ArticleHeader.tsx
Labels: refactor, FE

#271 [FE][BOM-376] 펫 비율 꺠짐 현상
  frontend/src/components/PetCard/PetCard.tsx
Labels: fix, FE
