Repository woowacourse-teams/2025-bom-bom, pull requests merged in 2025-07, with the labels that each got.

#8 docs: gitignore 파일 수정
  .gitignore
Labels: docs

#6 [BE][BOM-23] feat: 뉴스레터 목록 조회 API 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/domain/Article.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/ContinueReading.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Role.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/WeeklyGoal.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/controller/NewsletterController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/Category.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/NewsLetter.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/Newsletter.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/NewsletterDetail.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/NewsletterDetailRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/NewsletterRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/service/NewsletterService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/subscribe/domain/Subscribe.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/newsletter/service/NewsletterServiceTest.java
Labels: feat

#17 [FE][BOM-42] feat: header component 제작
  frontend/.eslintrc.cjs
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/public/assets/compass.svg
  frontend/public/assets/copy.svg
  frontend/public/assets/home.svg
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/icons/CompassIcon.tsx
  frontend/src/components/icons/CopyIcon.tsx
  frontend/src/components/icons/HomeIcon.tsx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/header.css
  frontend/tsconfig.json
Labels: FE

#16 [FE][BOM-38] feat: article component 제작
  frontend/jest.config.cjs
  frontend/package-lock.json
  frontend/public/assets/clock.svg
  frontend/src/App.tsx
  frontend/src/pages/today/components/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCars.stories.tsx
  frontend/src/pages/today/types/article.ts
  frontend/src/svg.d.ts
  frontend/src/utils/date.test.ts
  frontend/src/utils/date.ts
  frontend/tsconfig.json
Labels: feat, FE

#23 [FE][BOM-65] feat: ReadingKingLeaderBoard component 제작
  frontend/src/components/icons/AvatarIcon.tsx
  frontend/src/components/icons/BookIcon.tsx
  frontend/src/components/icons/TopRightArrowIcon.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.stories.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
Labels: feat, FE

#18 [FE][BOM-61] fix: stylelint 오류 해결
  frontend/.stylelintrc.cjs
  frontend/.stylelintrc.json
  frontend/src/App.tsx
  frontend/src/components/Badge/Badge.tsx
  frontend/src/components/Chip/Chip.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/ImageInfoCard/ImageInfoCard.tsx
  frontend/src/components/NewsletterHero/NewsletterHero.tsx
  frontend/src/components/ProgressBar.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
  frontend/src/pages/today/components/ArticleCard.tsx
  frontend/src/pages/today/components/ReadingStatusCard.tsx
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Button.tsx
  frontend/src/stories/Configure.mdx
  frontend/src/stories/assets/accessibility.png
  frontend/src/stories/assets/accessibility.svg
  frontend/src/stories/assets/addon-library.png
  frontend/src/stories/assets/assets.png
  frontend/src/stories/assets/avif-test-image.avif
  frontend/src/stories/assets/context.png
  frontend/src/stories/assets/discord.svg
  frontend/src/stories/assets/docs.png
  frontend/src/stories/assets/figma-plugin.png
  frontend/src/stories/assets/github.svg
  frontend/src/stories/assets/share.png
  frontend/src/stories/assets/styling.png
  frontend/src/stories/assets/testing.png
  frontend/src/stories/assets/theming.png
  frontend/src/stories/assets/tutorials.svg
  frontend/src/stories/assets/youtube.svg
  frontend/src/stories/button.css
  frontend/src/stories/page.css
  frontend/src/styles/theme.ts
Labels: fix, FE

#27 [BE][BOM-71] chore: ci 파이프라인 구축
  backend/bom-bom-server/.github/workflow/dev-deploy.yml
Labels: chore, BE

#28 [BE][BOM-71] chore: ci 파이프라인 수정
  backend/bom-bom-server/.github/workflow/dev-deploy.yml
Labels: chore, BE

#30 [FE][BOM-45] feat: today page 제작
  frontend/public/assets/check.svg
  frontend/public/assets/letter.svg
  frontend/src/App.tsx
  frontend/src/components/Header/Header.stories.tsx
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/mocks/data/mock-articles.ts
  frontend/src/pages/today/components/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList.tsx
  frontend/src/pages/today/components/ReadingStatusCard.tsx
  frontend/src/routes/__root.tsx
  frontend/src/routes/index.tsx
  frontend/src/styles/reset.ts
  frontend/src/types/nav.ts
Labels: feat, FE

#32 [FE][BOM-75] feat: SearchInput component 제작
  frontend/src/components/SearchInput/SearchInput.stories.tsx
  frontend/src/components/SearchInput/SearchInput.tsx
  frontend/src/components/icons/ReadingGlassesIcon.tsx
Labels: feat, FE

#34 [FE][BOM-74] feat: ProgressWithLabel component 제작
  frontend/src/components/ProgressBar/ProgressBar.stories.ts
  frontend/src/components/ProgressBar/ProgressBar.tsx
  frontend/src/components/ProgressWithLabel/ProgressWithLabel.stories.ts
  frontend/src/components/ProgressWithLabel/ProgressWithLabel.tsx
  frontend/src/components/ProgressWithLabel/progress.ts
  frontend/src/components/ProgressWithLabel/types.ts
  frontend/src/pages/today/components/ReadingStatusCard.tsx
  frontend/src/utils/math.ts
Labels: feat, FE

#37 [FE][BOM-73] feat: Assignee 및 Reviewer 자동 배정
  .github/auto_assign_backend.yml
  .github/auto_assign_frontend.yml
  .github/workflows/auto_assign.yml
Labels: feat

#38 [BE][BOM-87] feat: 카테고리 별 아티클 개수 조회 API 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCategoryStatisticsResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticleCountPerCategoryResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/service/ArticleServiceTest.java
Labels: feat, BE

#40 [FE][BOM-46] feat: 뉴스레터 추천 페이지 레이아웃
  frontend/public/assets/trending-up.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/constants/category.ts
  frontend/src/mocks/trendyNewsLetter.ts
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/NewsletterHero/NewsletterHero.stories.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/NewsletterHero/NewsletterHero.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/routes/recommend.tsx
Labels: feat, FE

#46 [FE][BOM-96] feat: 페이지 라우팅
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/today/components/ArticleCard.tsx
  frontend/src/styles/reset.ts
Labels: feat, FE

#41 [FE][BOM-76] feat: Category component 제작
  frontend/public/assets/category.svg
  frontend/src/components/Tab/Tab.stories.tsx
  frontend/src/components/Tab/Tab.tsx
  frontend/src/components/Tabs/Tabs.stories.tsx
  frontend/src/components/Tabs/Tabs.tsx
  frontend/src/components/icons/CategoryIcon.tsx
  frontend/src/pages/archive/components/CategoryFilter/CategoryFilter.stories.tsx
  frontend/src/pages/archive/components/CategoryFilter/CategoryFilter.tsx
Labels: feat, FE

#45 [FE][BOM-95] feat: 절대 경로 설정
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Header/Header.tsx
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/components/ProgressWithLabel/progress.ts
  frontend/src/components/SearchInput/SearchInput.tsx
  frontend/src/components/Select/Select.tsx
  frontend/src/pages/archive/components/CategoryFilter/CategoryFilter.tsx
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.stories.tsx
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.tsx
  frontend/src/pages/login/components/LoginCard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/today/apis/getTodayArticles.ts
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCard.tsx
  frontend/tsconfig.json
  frontend/webpack.config.cjs
Labels: feat, FE

#49 [BE][BOM-101] fix: 뉴스레터 이메일 길이 제한 증가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/domain/Newsletter.java
Labels: fix, BE

#48 [FE][BOM-81] feat: article storage 페이지 제작
  frontend/public/assets/storage.svg
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Tab/Tab.stories.tsx
  frontend/src/components/Tab/Tab.tsx
  frontend/src/components/icons/StorageIcon.tsx
  frontend/src/constants/category.ts
  frontend/src/pages/storage/components/CategoryFilter/CategoryFilter.stories.tsx
  frontend/src/pages/storage/components/CategoryFilter/CategoryFilter.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/storage.tsx
  frontend/src/types/nav.ts
Labels: feat, FE

#52 [FE][BOM-108] feat: enable msw 설정
  frontend/package.json
  frontend/src/apis/env.ts
  frontend/src/main.tsx
  frontend/webpack.config.cjs
Labels: feat, FE

#55 [FE][BOM-99] feat: login 기능 추가
  frontend/src/pages/login/components/LoginCard.tsx
Labels: feat, FE

#35 [FE][BOM-73] feat: Frontend CI 작성
  .github/pull_request_template.md
  .github/workflows/frontend-ci-cd.yml
Labels: feat, FE

#58 [FE][BOM-73] 안읽은 뉴스테러 실제 api 연결
  .github/workflows/frontend-ci-cd.yml
  frontend/src/apis/ApiError.ts
  frontend/src/apis/articles.ts
  frontend/src/apis/fetcher.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Tabs/Tabs.stories.tsx
  frontend/src/components/Tabs/Tabs.tsx
  frontend/src/pages/detail/components/NewsletterItemCard/NewsletterItemCard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/routes/articles.$articleId.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/recommend.tsx
  frontend/src/routes/storage.tsx
Labels: feat, FE

#59 [FE][BOM-117] feat: category sort filter 기능 추가
  frontend/src/apis/articles.ts
  frontend/src/apis/fetcher.ts
  frontend/src/components/Tabs/Tabs.stories.tsx
  frontend/src/mocks/article.ts
  frontend/src/mocks/data/mock-articles.ts
  frontend/src/pages/storage/utils/getArticleReadStats.ts
  frontend/src/pages/today/components/ArticleCard/ArticleCard.stories.tsx
  frontend/src/pages/today/components/ArticleCard/ArticleCard.tsx
  frontend/src/pages/today/types/article.ts
  frontend/src/pages/today/types/category.ts
  frontend/src/routes/articles.$articleId.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/storage.tsx
  frontend/src/utils/date.test.ts
  frontend/src/utils/date.ts
Labels: feat, FE

#63 [BE][BOM-102] feat: 제목 검색 기능 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticlesOptions.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/enums/SortOption.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/TestFixture.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/domain/ArticleTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/service/ArticleServiceTest.java
Labels: feat, BE

#65 [BE][BOM-128] fix: 아티클 상세 조회 반환값에 isRead 필드 추가
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/ArticleDetailResponse.java
Labels: fix, BE

#66 [FE][BOM-119] feat: article read 기능 구현
  frontend/src/apis/articles.ts
  frontend/src/apis/fetcher.ts
  frontend/src/hooks/useThrottle.ts
  frontend/src/pages/detail/types/articleDetail.ts
  frontend/src/routes/articles.$articleId.tsx
  frontend/src/routes/index.tsx
  frontend/src/utils/scroll.test.ts
  frontend/src/utils/scroll.ts
  frontend/webpack.config.cjs
Labels: feat, FE

#68 [FE][BOM-130] feat: category 필터링 name으로 변경
  frontend/src/routes/storage.tsx
Labels: feat, FE

#69 [BE][BOM-131] feat: 구글 로그인 후 리다이렉트 기능 구현
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/handler/OAuth2LoginSuccessHandler.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/SecurityConfig.java
Labels: feat, BE

#71 [FE][BOM-137] feat: 뉴스레터 추천 페이지 필터링 기능
  frontend/src/constants/category.ts
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/TrendySection/TrendySection.tsx
  frontend/src/pages/today/types/article.ts
  frontend/src/routes/recommend.tsx
Labels: feat, FE

#67 [FE][BOM-119] feat: 로그인 라우팅
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/NewsletterHero/NewsletterHero.tsx
  frontend/src/routes/index.tsx
Labels: feat, FE

#73 [FE][BOM-135] feat: article search 기능 추가
  frontend/src/apis/articles.ts
  frontend/src/components/SearchInput/SearchInput.stories.tsx
  frontend/src/components/SearchInput/SearchInput.tsx
  frontend/src/hooks/useDebounce.ts
  frontend/src/hooks/useThrottle.ts
  frontend/src/routes/storage.tsx
Labels: feat, FE

#78 [FE][BOM-97] feat: frontend cd 빌드 파일 추가
  .gitignore
  frontend/buildspec.yml
Labels: feat, FE

#81 [FE][BOM-152] test: 테스트가 깨지는 현상 수정
  frontend/src/utils/date.test.ts
  frontend/src/utils/math.test.ts
Labels: test, FE

#86 [FE][BOM-160] fix: 디바운싱 타임 수정
  frontend/src/routes/storage.tsx
Labels: fix, FE

#79 [FE][BOM-134] feat: EmptyLetterCard 컴포넌트 생성
  frontend/public/assets/arrow.svg
  frontend/public/assets/postbox.svg
  frontend/src/components/Select/Select.tsx
  frontend/src/components/icons/ArrowIcon.tsx
  frontend/src/components/icons/ChevronIcon.tsx
  frontend/src/components/icons/Icons.constants.ts
  frontend/src/components/icons/Icons.types.ts
  frontend/src/components/icons/Icons.utils.ts
  frontend/src/components/icons/PostboxIcon.tsx
  frontend/src/components/icons/TopRightArrowIcon.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
  frontend/src/pages/today/components/EmptyLetterCard/EmptyLetterCard.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/storage.tsx
Labels: feat, FE

#83 [FE][BOM-150] fix: 웹팩 타입 에러 해결
  frontend/.eslintrc.cjs
  frontend/jest.config.cjs
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.ts
Labels: fix, FE

#88 [BE][BOM-161] 회원가입 시 이메일 입력
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/request/MemberSignupRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/repository/MemberRepository.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/service/MemberServiceTest.java
Labels: fix, BE

#92 [FE][BOM-163] chore: memeberId 제거
  frontend/src/apis/articles.ts
  frontend/src/apis/members.ts
  frontend/src/routes/articles.$articleId.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/storage.tsx
Labels: chore, FE

#91 [FE][BOM-162] feat: header login/signup에만 보이게 변경
  frontend/src/components/PageLayout/PageLayout.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/_bombom.tsx
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/routes/_bombom/index.tsx
  frontend/src/routes/_bombom/recommend.tsx
  frontend/src/routes/_bombom/storage.tsx
  frontend/src/routes/recommend.tsx
Labels: refactor, FE

#99 [FE][BOM-167] feat: signup 기능 구현
  frontend/src/apis/auth.ts
  frontend/src/apis/fetcher.ts
  frontend/src/apis/members.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/signup/components/SignupCard.tsx
  frontend/src/routeTree.gen.ts
  frontend/src/routes/articles.$articleId.tsx
  frontend/src/routes/index.tsx
  frontend/src/routes/signup.tsx
  frontend/src/routes/storage.tsx
Labels: feat, FE

#94 feat: 깃헙 Reviewer 알림 슬랙봇
  .github/reviewers.json
  .github/workflows/pr_reviewer.yml
Labels: feat

#80 [FE][BOM-51] feat: Playwright 세팅
  frontend/.gitignore
  frontend/e2e/articles.spec.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/playwright.config.ts
Labels: feat, FE

#101 feat: 이메일 복사 시 alert
  frontend/src/components/Header/Header.tsx
Labels: feat, FE

#95 [BE][BOM-86] feat: 이메일 서버 구축
  .github/workflows/email-dev-deploy.yml
  backend/mail-server/Dockerfile
  backend/mail-server/build.gradle.kts
  backend/mail-server/docker-compose.yml
  backend/mail-server/gradle/wrapper/gradle-wrapper.properties
  backend/mail-server/maildir/cur/.gitkeep
  backend/mail-server/maildir/new/.gitkeep
  backend/mail-server/maildir/parsing-failed/.gitkeep
  backend/mail-server/maildir/tmp/.gitkeep
  backend/mail-server/src/main/java/news/bombomemail/BomBomEmailServerApplication.java
  backend/mail-server/src/main/java/news/bombomemail/article/domain/Article.java
  backend/mail-server/src/main/java/news/bombomemail/article/repository/ArticleRepository.java
  backend/mail-server/src/main/java/news/bombomemail/article/service/ArticleService.java
  backend/mail-server/src/main/java/news/bombomemail/article/util/ReadingTimeCalculator.java
  backend/mail-server/src/main/java/news/bombomemail/article/util/SummaryGenerator.java
  backend/mail-server/src/main/java/news/bombomemail/common/BaseEntity.java
  backend/mail-server/src/main/java/news/bombomemail/email/EmailConfig.java
  backend/mail-server/src/main/java/news/bombomemail/email/EmailIntegrationConfig.java
  backend/mail-server/src/main/java/news/bombomemail/email/service/EmailService.java
  backend/mail-server/src/main/java/news/bombomemail/email/util/EmailContentExtractor.java
  backend/mail-server/src/main/java/news/bombomemail/member/domain/Gender.java
  backend/mail-server/src/main/java/news/bombomemail/member/domain/Member.java
  backend/mail-server/src/main/java/news/bombomemail/member/repository/MemberRepository.java
  backend/mail-server/src/main/java/news/bombomemail/newsletter/domain/Newsletter.java
  backend/mail-server/src/main/java/news/bombomemail/newsletter/repository/NewsletterRepository.java
  backend/mail-server/src/test/java/me/bombom/BomBomServerApplicationTests.java
  backend/mail-server/src/test/java/news/bombomemail/article/ArticleServiceTest.java
  backend/mail-server/src/test/java/news/bombomemail/email/service/EmailServiceTest.java
  backend/mail-server/src/test/resources/sample.eml
  backend/mail-server/src/test/resources/sample_invalid.eml
  backend/mail-server/src/test/resources/sample_multi_1.eml
  backend/mail-server/src/test/resources/sample_multi_2.eml
  backend/mail-server/src/test/resources/sample_no_body.eml
  backend/mail-server/src/test/resources/sample_no_subject.eml
Labels: feat, BE

#103 [FE][BOM-158] feat: EmptySearchCard 컴포넌트 생성
  frontend/public/assets/empty-search.svg
  frontend/src/components/icons/EmptySearchIcon.tsx
  frontend/src/pages/storage/components/EmptySearchCard/EmptySearchCard.tsx
  frontend/src/routes/_bombom/storage.tsx
Labels: feat, FE

#102 [BE][BOM-164] feat: 회원가입 시 읽기 정보 초기화
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/resolver/LoginMemberArgumentResolver.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupEvent.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/service/MemberService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/member/event/MemberSignupListenerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/service/ReadingServiceTest.java
Labels: feat, BE

#107 [BE][BOM-186] fix: 읽기 정보 초기화 이벤트 버그 수정
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/event/MemberSignupListener.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/reading/service/ReadingService.java
Labels: fix, BE

#109 [FE][BOM-185] feat: login routing 기능 수정
  frontend/src/main.tsx
  frontend/src/routes/__root.tsx
  frontend/src/routes/_bombom.tsx
Labels: feat, FE

#117 [FE][BOM-193] fix: route tree 오류 해결
  frontend/src/routeTree.gen.ts
Labels: fix, FE

#112 [FE][BOM-187] feat: 검색 결과에 따른 category 개수 업데이트
  frontend/src/apis/articles.ts
  frontend/src/apis/fetcher.ts
  frontend/src/hooks/useDebouncedValue.ts
  frontend/src/routes/_bombom/storage.tsx
Labels: feat, FE

#116 [FE][BOM-188] feat: today page loading 처리 및 리팩토링
  frontend/.vscode/settings.json
  frontend/src/pages/today/components/ArticleCardList/ArticleCardList.tsx
  frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCard.tsx
  frontend/src/pages/today/components/ReadingStatusCard/ReadingStatusCardSkeleton.tsx
  frontend/src/routes/_bombom/index.tsx
Labels: refactor, FE

#110 [FE][BOM-189] fix: 스크롤이 없을 경우 바로 읽음 처리
  frontend/src/hooks/useScrollThreshold.ts
  frontend/src/routes/_bombom/articles.$articleId.tsx
  frontend/src/utils/scroll.ts
Labels: fix, FE

#106 [FE][BOM-174] chore: 스토리북 빌드 및 배포 자동화
  .github/workflows/chromatic.yml
Labels: chore, FE

#114 [BE][BOM-175] fix: 동적 쿼리 Querydsl로 수정
  backend/bom-bom-server/build.gradle.kts
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/controller/ArticleController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/ArticleResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/dto/GetArticlesOptions.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/enums/SortOption.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/repository/ArticleRepositoryImpl.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/article/service/ArticleService.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/auth/controller/AuthController.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/common/config/QuerydslConfig.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/dto/request/MemberSignupRequest.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/dto/NewsletterSummaryResponse.java
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/newsletter/repository/CategoryRepository.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/controller/ArticleControllerTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/article/service/ArticleServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/newsletter/service/NewsletterServiceTest.java
  backend/bom-bom-server/src/test/java/me/bombom/api/v1/reading/service/ReadingServiceTest.java
Labels: fix, BE

#120 [BE][BOM-195] chore: 개발용 Docker Compse 분리
  .github/workflows/dev-deploy.yml
  backend/bom-bom-server/docker-compose-dev.yml
Labels: chore, BE
