Repository woowacourse-teams/2025-bom-bom, pull requests merged in 2025-10, with the labels that each got.

#410 [BE][BOM-517] fix: 회원 테이블 deleted_at 필드 제거
  backend/bom-bom-server/src/main/java/me/bombom/api/v1/member/domain/Member.java
  backend/bom-bom-server/src/main/resources/db/migration/V6.7.0__remove_member_deleted_at_field.sql
Labels: fix, BE

#419 [FE][BOM-533] expo 버전에 맞게 패키지 업데이트
  app/app.config.js
  app/package-lock.json
  app/package.json
Labels: fix, FE

#414 [FE][BOM-524] 회원탈퇴 후 로그인 정보가 업데이트 되도록 개선
  frontend/src/components/Header/ProfileDetail.tsx
Labels: refactor, FE

#428 [FE][BOM-539] chore: 랭킹 컴포넌트 캐러셀 동작 및 보드 UI 개선
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboard.tsx
  frontend/src/pages/recommend/components/ReadingKingLeaderboard/ReadingKingLeaderboardSkeleton.tsx
Labels: chore, FE

#431 [FE][BOM-540] feat: carousel 스와이프 기능 추가 및 UI 수정
  frontend/public/assets/avif/carousel-arrow-next.avif
  frontend/public/assets/avif/carousel-arrow-prev.avif
  frontend/public/assets/svg/chevron-down.svg
  frontend/src/components/Carousel/Carousel.constants.ts
  frontend/src/components/Carousel/Carousel.tsx
  frontend/src/components/Carousel/useCarousel.ts
Labels: feat, FE
